SELECT * FROM CUSTOMER;

--Total revenue by each gender
SELECT GENDER AS GENDER,SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY GENDER;

--Which customers used discount and still paid more than average purchase amount
SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER;

SELECT CUSTOMER_ID, DISCOUNT_APPLIED, PURCHASE_AMOUNT
FROM CUSTOMER 
WHERE DISCOUNT_APPLIED = 'Yes' 
AND PURCHASE_AMOUNT > 
(SELECT AVG(PURCHASE_AMOUNT) 
FROM CUSTOMER);

--TOP 5 Products with highest Average Review Rating
SELECT ITEM_PURCHASED, ROUND(AVG(REVIEW_RATING::NUMERIC),2) AS AVG_REVIEW_RATING
FROM CUSTOMER
GROUP BY ITEM_PURCHASED 
ORDER BY AVG_REVIEW_RATING DESC
LIMIT 5;

--COMPARE AVG PURCHASE AMOUNT BETWEEN STANDARD AND EXPRESS SHIPPING
SELECT SHIPPING_TYPE, ROUND(AVG(PURCHASE_AMOUNT),2) 
FROM CUSTOMER
WHERE SHIPPING_TYPE IN ('Standard','Express')
GROUP BY SHIPPING_TYPE;

--Do subscribed customers spend more. Compare avg spend and total_revenue between subscribers and non-subscribers
SELECT 
SUBSCRIPTION_STATUS, COUNT(CUSTOMER_ID),
SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE, 
ROUND(AVG(PURCHASE_AMOUNT),2) AS AVG_SPEND
FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS;

--5 Products that has highest percentage of purchases with discounts
SELECT ITEM_PURCHASED, 
ROUND(100 * SUM(CASE WHEN DISCOUNT_APPLIED = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS DISCOUNT_RATE
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;

--Segment customer into New, Returning, Loyal based on their total numer of previous purchases and show the count of each segment
WITH CUSTOMER_TYPE AS (
	SELECT CUSTOMER_ID, PREVIOUS_PURCHASES,
	CASE
		WHEN PREVIOUS_PURCHASES =1 THEN 'NEW'
		WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'RETURNING'
		ELSE 'LOYAL'
	END AS CUSTOMER_SEGMENT
	FROM CUSTOMER
)
SELECT CUSTOMER_SEGMENT, COUNT(CUSTOMER_SEGMENT)
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT;


--Top 3 most purchased products within each category
WITH ITEM_COUNTS AS (
	SELECT 
	CATEGORY, 
	ITEM_PURCHASED, 
	COUNT(CUSTOMER_ID) AS TOTAL_ORDERS,
	ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY COUNT(CUSTOMER_ID) DESC ) AS ITEM_RANK
	FROM CUSTOMER
	GROUP BY CATEGORY, ITEM_PURCHASED
)

SELECT ITEM_RANK, CATEGORY, ITEM_PURCHASED, TOTAL_ORDERS
FROM ITEM_COUNTS
WHERE ITEM_RANK <=3;

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT SUBSCRIPTION_STATUS,
COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM CUSTOMER
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS;

--REVENUE CONTRIBUTION OF EACH AGE GROUP
SELECT AGE_GROUP, SUM(purchase_amount) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY AGE_GROUP
ORDER BY TOTAL_REVENUE DESC;